jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "incentergy.ol.library-preload",
	"modules": {
		"incentergy/ol/Feature.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"sap/ui/base/ManagedObject\"],function(e,t){\"use strict\";var r=new e.format.WKT;return t.extend(\"incentergy.ol.Feature\",{metadata:{library:\"incentergy.ol\",properties:{wkt:{type:\"string\",defaultValue:null}}},constructor:function(){this._feature=new e.Feature;var r=this;this._pLayerSet=new Promise(function(e,t){r._fnLayerSet=e}),t.apply(this,arguments)},setParent:function(e){var r=this;return e.mapSet().then(function(){e.getParent().mapSet().then(function(){e._source.addFeature(r._feature)}),r._fnLayerSet()}),t.prototype.setParent.apply(this,arguments)},_layerSet:function(){return this._pLayerSet},setWkt:function(e){var t=this;this._layerSet().then(function(){var n=t.getParent();n.mapSet().then(function(){n.getParent().mapSet().then(function(){n._source.removeFeature(t._feature),t._feature=r.readFeature(e,{dataProjection:\"EPSG:4326\",featureProjection:\"EPSG:3857\"}),n._source.addFeature(t._feature)})})}),this.setProperty(\"wkt\",e)}})},!0);",
		"incentergy/ol/Map.js": "sap.ui.define([\"ol\",\"sap/ui/core/Control\"],function(e,t){\"use strict\";return t.extend(\"incentergy.ol.Map\",{metadata:{library:\"incentergy.ol\",properties:{},defaultAggregation:\"layers\",aggregations:{layers:{type:\"incentergy.ol.layer.Base\",multiple:!0,singularName:\"layer\"}}},init:function(){var e=this;this._pRendered=new Promise(function(t,n){e._fnRendered=t}),sap.ui.getCore().attachThemeChanged(function(){e._map&&e._map.updateSize()})},renderer:function(e,t){e.write('<div style=\"height: 100%\" '),e.writeControlData(t),e.write(\">\"),e.write(\"</div>\")},onAfterRendering:function(){this._fnRendered(),this._map=new e.Map({view:new e.View({center:[0,0],zoom:1}),target:this.getId()})},_rendered:function(){return this._pRendered},viewFit:function(e){var t=this;this._rendered().then(function(){t._map.getView().fit(e)})}})},!0);",
		"incentergy/ol/layer/Base.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"sap/ui/base/Object\",\"sap/ui/base/ManagedObject\",\"sap/ui/Device\",\"jquery.sap.strings\",\"jquery.sap.trace\"],function(t,e,a,n){\"use strict\";return a.extend(\"incentergy.ol.layer.Base\",{metadata:{abstract:!0},constructor:function(){var t=this;this.pMapSet=new Promise(function(e,a){t.fnMapSet=e}),a.apply(this,arguments)},setParent:function(t){var e=this;t._rendered().then(function(){t._map.addLayer(e._layer)});var n=a.prototype.setParent.apply(this,arguments);return this.fnMapSet(),n},mapSet:function(){return this.pMapSet}})},!0);",
		"incentergy/ol/layer/Layer.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./Base\"],function(e,t){\"use strict\";return t.extend(\"incentergy.ol.layer.Layer\",{metadata:{properties:{}}})},!0);",
		"incentergy/ol/layer/Tile.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./Layer\"],function(e,r){\"use strict\";return r.extend(\"incentergy.ol.layer.Tile\",{metadata:{properties:{},defaultAggregation:\"source\",aggregations:{source:{type:\"incentergy.ol.source.Tile\",multiple:!1,singularName:\"source\"}}},constructor:function(t){r.apply(this,arguments),this._layer=new e.layer.Tile({source:this.getSource()._source})}})},!0);",
		"incentergy/ol/layer/Vector.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./Layer\"],function(e,r){\"use strict\";return r.extend(\"incentergy.ol.layer.Vector\",{metadata:{properties:{},defaultAggregation:\"source\",aggregations:{source:{type:\"incentergy.ol.source.Vector\",multiple:!1,singularName:\"source\"}}},constructor:function(t){r.apply(this,arguments),this._layer=new e.layer.Vector({source:this.getSource()._source})}})},!0);",
		"incentergy/ol/library.js": "/*!\n * ${copyright}\n */\nsap.ui.define([],function(){\"use strict\";return sap.ui.getCore().initLibrary({name:\"incentergy.ol\",version:\"4.1.0\",dependencies:[\"sap.ui.core\"],types:[],interfaces:[],controls:[\"incentergy.ol.Map\",\"incentergy.ol.Feature\",\"incentergy.ol.layer.Base\",\"incentergy.ol.layer.Layer\",\"incentergy.ol.layer.Tile\",\"incentergy.ol.layer.Vector\",\"incentergy.ol.source.Vector\",\"incentergy.ol.source.OSM\",\"incentergy.ol.source.Tile\",\"incentergy.ol.source.UrlTile\",\"incentergy.ol.source.TileImage\",\"incentergy.ol.source.XYZ\"],elements:[\"incentergy.ol.geom.Point\",\"incentergy.ol.geom.Polygon\"]}),incentergy.ol},!1);",
		"incentergy/ol/source/OSM.js": "sap.ui.define([\"ol\",\"./XYZ\"],function(e,t){\"use strict\";return t.extend(\"incentergy.ol.source.OSM\",{metadata:{library:\"incentergy.ol\"},constructor:function(){t.apply(this,arguments),this._source=new e.source.OSM({url:this.getUrl()})}})},!0);",
		"incentergy/ol/source/Source.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"sap/ui/base/ManagedObject\"],function(t,e){\"use strict\";return e.extend(\"incentergy.ol.source.Source\",{metadata:{library:\"incentergy.ol\",abstract:!0},constructor:function(){var t=this;this.pMapSet=new Promise(function(e,n){t.fnMapSet=e}),e.apply(this,arguments)},setParent:function(t){var n=this,a=e.prototype.setParent.apply(this,arguments);return t.mapSet().then(function(){n.fnMapSet()}),a},mapSet:function(){return this.pMapSet}})},!0);",
		"incentergy/ol/source/Tile.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./Source\"],function(e,t){\"use strict\";return t.extend(\"incentergy.ol.source.Tile\",{metadata:{library:\"incentergy.ol\",abstract:!0}})},!0);",
		"incentergy/ol/source/TileImage.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./UrlTile\"],function(e,r){\"use strict\";return r.extend(\"incentergy.ol.source.TileImage\",{metadata:{library:\"incentergy.ol\",abstract:!0,properties:{url:{type:\"string\",group:\"Misc\",defaultValue:null}}}})},!0);",
		"incentergy/ol/source/UrlTile.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./Tile\"],function(e,t){\"use strict\";return t.extend(\"incentergy.ol.source.UrlTile\",{metadata:{library:\"incentergy.ol\",abstract:!0}})},!0);",
		"incentergy/ol/source/Vector.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./Source\"],function(e,t){\"use strict\";return t.extend(\"incentergy.ol.source.Vector\",{metadata:{library:\"incentergy.ol\",aggregations:{features:{type:\"incentergy.ol.Feature\",multiple:!0,singularName:\"feature\"}}},constructor:function(){t.apply(this,arguments),this._source=new e.source.Vector},getExtent:function(){return this._source.getExtent()}})},!0);",
		"incentergy/ol/source/XYZ.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"ol\",\"./TileImage\"],function(e,n){\"use strict\";return n.extend(\"incentergy.ol.source.XYZ\",{metadata:{library:\"incentergy.ol\"}})},!0);"
	}
});